name: AI CI Copilot

on:
  workflow_run:
    workflows: ["sync"]  # Your main CI workflow
    types:
      - completed

jobs:
  explain-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          sudo apt-get update && sudo apt-get install gh -y

      - name: Run AI CI Copilot
        id: runai
        run: |
          echo "🚀 Running AI log analysis..."
          OUTPUT=$(python scripts/analyze_failure.py)
          echo "$OUTPUT"
          echo "AI_COMMENT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on Commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=${{ github.event.workflow_run.head_sha }}
          COMMENT=$(echo "$AI_COMMENT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$COMMENT\"}" \
            https://api.github.com/repos/${{ github.repository }}/commits/$SHA/comments

      - name: Comment on Pull Request (if exists)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHA=${{ github.event.workflow_run.head_sha }}
          REPO=${{ github.repository }}

          PR_NUMBER=$(gh pr list --repo "$REPO" --state open --json number,commits --jq ".[] | select(.commits[].oid==\"$SHA\") | .number")

          if [ -z "$PR_NUMBER" ]; then
            echo "ℹ️ No matching PR found for commit $SHA"
            exit 0
          fi

          COMMENT=$(echo "$AI_COMMENT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$COMMENT\"}" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments
