name: AI Groq Repo Review

on:
  push:
    branches: [main]
  pull_request:

jobs:
  groq-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Groq AI Review
        run: |
          python3 scripts/groq_review.py || true
