name: AI Groq Repo Review

on:
  push:
    branches: [main]

jobs:
  groq-review:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: 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

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Run Groq AI Review
        run: python scripts/groq_review.py > ai_review.md

      - name: Comment with AI Suggestions
        run: |
          SHA=$(git rev-parse HEAD)
          COMMENT=$(cat ai_review.md | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          PR_API="https://api.github.com/repos/${{ github.repository }}/commits/$SHA/pulls"
          PR_URL=$(curl -s -H "Authorization: token $GH_TOKEN" "$PR_API" | jq -r 'if type=="array" and length > 0 then .[0].issue_url else empty end')

          if [ -n "$PR_URL" ]; then
            echo "📝 Commenting on PR..."
            curl -s -X POST -H "Authorization: token $GH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"$COMMENT\"}" "$PR_URL/comments"
          else
            echo "📝 Commenting on commit..."
            curl -s -X POST -H "Authorization: token $GH_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"$COMMENT\"}" \
              "https://api.github.com/repos/${{ github.repository }}/commits/$SHA/comments"
          fi
