# name: Mirror Repo A to Repo B

# on:
#   push:
#     branches:
#       - '**'
#     tags:
#       - '**'
#   create:
#     branches:
#       - '**'
#     tags:
#       - '**'
#   pull_request:
#     types: [closed]
#   workflow_dispatch:
#   schedule:
#     - cron: '0 */6 * * *'

# jobs:
#   mirror:
#     if: github.event.pull_request.merged == true || github.event_name != 'pull_request'
#     runs-on: ubuntu-latest

#     steps:
#       - name: Mirror clone and push
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           DESTINATION_REPO: ${{ secrets.DESTINATION_REPO }}
#         run: |
#           echo "Cloning Repo A as mirror..."
#           git clone --mirror https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} repo-mirror

#           cd repo-mirror

#           echo "Pushing mirror to Repo B..."
#           git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${DESTINATION_REPO}.git
#           git push --mirror --force

#           echo "✅ Mirror sync complete."
