name: Sync Repo A to Repo B

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - '**'
  pull_request:
    types:
      - closed

jobs:
  sync:
    if: github.event.pull_request.merged == true || github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git User
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "sync-bot@example.com"

      - name: Add destination repository and push
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Starting repository sync..."

          # Correct Remote URL with token inserted
          REMOTE_URL="https://x-access-token:${TOKEN}@github.com/abhishekvarale/Reposittory-B.git"

          echo "Setting up destination remote..."
          git remote add destination "$REMOTE_URL"

          echo "Verifying remotes:"
          git remote -v

          echo "Pushing all branches to destination repository..."
          git push destination --all --force

          echo "Pushing all tags to destination repository..."
          git push destination --tags --force

          echo "Repository sync completed successfully."

